"""empty message

Revision ID: 34ebc3be7428
Revises: 657be1061583
Create Date: 2026-03-05 16:32:44.912093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ebc3be7428'
down_revision: Union[str, Sequence[str], None] = '657be1061583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('v1_offset', sa.Float(), nullable=True),
    sa.Column('v2_offset', sa.Float(), nullable=True),
    sa.Column('v3_offset', sa.Float(), nullable=True),
    sa.Column('v4_offset', sa.Float(), nullable=True),
    sa.Column('v5_offset', sa.Float(), nullable=True),
    sa.Column('v6_offset', sa.Float(), nullable=True),
    sa.Column('v7_offset', sa.Float(), nullable=True),
    sa.Column('active_sensors', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_equipment_id'), 'devices', ['equipment_id'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_equipment_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
