"""empty message

Revision ID: 5714a9cab06a
Revises: 7c454727742e
Create Date: 2026-03-06 12:14:42.224189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5714a9cab06a'
down_revision: Union[str, Sequence[str], None] = '7c454727742e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('min_voltage', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('last_v7', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('last_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_state')
    op.drop_column('devices', 'last_v7')
    op.drop_column('devices', 'min_voltage')
    # ### end Alembic commands ###
